version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: ./.docker/entrypoint.sh
    networks:
      - node-network
      - app-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - node_db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: node_nginx
    networks:
      - app-network
    ports:
      - 8080:80
    depends_on:
      - app

  node_db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
  app-network:
    driver: bridge
